### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hariads**
added 3 more quizes

### CODE REVIEW

**Comment by thedaviddias** [comment]
Hi @hariads, thanks to participating to the repo. However, I disagree to add quizzes for level "medium" and think it's better to stay with beginners only.

I'm already planning a list of resources for intermediates / advanced.

**Comment by Anandesh-Sharma** [comment]
Can you please tell me that, how can i get pluralsight tutorials is it free...?

**Comment by thedaviddias** [comment]
@Anandesh-Sharma, as mentioned on the list, Pluralsight videos are accessible with a paid subscription. Sorry.

**Comment by thedaviddias** [comment]
Closing invalid pull requests. No response from the author.

**Pull request closed without merging**
